[2024-03-05T21:13:44.067+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T21:13:44.071+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T21:13:44.072+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-03-05T21:13:44.078+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-05T21:13:44.082+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2024-03-05T21:13:44.084+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmp3vuokqnx']
[2024-03-05T21:13:44.085+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask download_dataset
[2024-03-05T21:13:44.109+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:13:44.133+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:13:44.134+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:13:44.137+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240305T211344, end_date=20240305T211344
[2024-03-05T21:13:44.144+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task download_dataset ('str object' has no attribute 'strftime'; 186)
[2024-03-05T21:13:44.175+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:13:44.191+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-07T13:46:22.486+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T13:46:22.491+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T13:46:22.491+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-03-07T13:46:22.498+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T13:46:22.501+0000] {standard_task_runner.py:60} INFO - Started process 573 to run task
[2024-03-07T13:46:22.503+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmph57wpuno']
[2024-03-07T13:46:22.504+0000] {standard_task_runner.py:88} INFO - Job 129: Subtask download_dataset
[2024-03-07T13:46:22.529+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 0430cbdaac75
[2024-03-07T13:46:22.555+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T13:46:22.667+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T13:46:22.668+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T13:46:22.668+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T13:46:22.674+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T13:46:22.675+0000] {subprocess.py:93} INFO - 
[2024-03-07T13:46:22.675+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T13:46:22.679+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T13:46:22.680+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T13:46:25.530+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 1820k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0 70 1820k   70 1274k    0     0   466k      0  0:00:03  0:00:02  0:00:01  466k100 1820k  100 1820k    0     0   638k      0  0:00:02  0:00:02 --:--:--  638k
[2024-03-07T13:46:25.533+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T13:46:25.574+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T13:46:25.575+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T13:46:25.746+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T13:46:25.747+0000] {subprocess.py:93} INFO - LOCAL_PATH=/opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T13:46:25.747+0000] {subprocess.py:93} INFO - 
[2024-03-07T13:46:25.747+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T13:46:25.747+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T13:46:25.763+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T134622, end_date=20240307T134625
[2024-03-07T13:46:25.807+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T13:46:25.819+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-07T14:15:37.307+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T14:15:37.311+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T14:15:37.312+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-03-07T14:15:37.318+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T14:15:37.321+0000] {standard_task_runner.py:60} INFO - Started process 1857 to run task
[2024-03-07T14:15:37.323+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmp4c1zvc2s']
[2024-03-07T14:15:37.324+0000] {standard_task_runner.py:88} INFO - Job 192: Subtask download_dataset
[2024-03-07T14:15:37.349+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 0430cbdaac75
[2024-03-07T14:15:37.377+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T14:15:37.501+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T14:15:37.502+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T14:15:37.502+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T14:15:37.508+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T14:15:37.509+0000] {subprocess.py:93} INFO - 
[2024-03-07T14:15:37.509+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T14:15:37.514+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T14:15:37.514+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T14:15:40.156+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  3 1820k    3 69228    0     0  36559      0  0:00:50  0:00:01  0:00:49 36551100 1820k  100 1820k    0     0   688k      0  0:00:02  0:00:02 --:--:--  689k
[2024-03-07T14:15:40.158+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T14:15:40.201+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T14:15:40.201+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T14:15:40.371+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T14:15:40.372+0000] {subprocess.py:93} INFO - 
[2024-03-07T14:15:40.372+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T14:15:40.373+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T14:15:40.373+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T14:15:40.386+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T141537, end_date=20240307T141540
[2024-03-07T14:15:40.425+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T14:15:40.439+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-07T18:41:15.458+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T18:41:15.549+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T18:41:15.549+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-03-07T18:41:15.557+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T18:41:15.560+0000] {standard_task_runner.py:60} INFO - Started process 1873 to run task
[2024-03-07T18:41:15.563+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmp6kgxgj8c']
[2024-03-07T18:41:15.564+0000] {standard_task_runner.py:88} INFO - Job 264: Subtask download_dataset
[2024-03-07T18:41:15.592+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host a0c898e5643f
[2024-03-07T18:41:15.619+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T18:41:15.635+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T18:41:15.637+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T18:41:15.638+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T18:41:15.645+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T18:41:15.646+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:41:15.646+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T18:41:15.651+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T18:41:15.651+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T18:41:17.274+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  1 1820k    1 34302    0     0  42231      0  0:00:44 --:--:--  0:00:44 42191100 1820k  100 1820k    0     0  1121k      0  0:00:01  0:00:01 --:--:-- 1122k
[2024-03-07T18:41:17.277+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T18:41:17.329+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T18:41:17.329+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T18:41:17.521+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T18:41:17.524+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:41:17.524+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T18:41:17.524+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T18:41:17.525+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T18:41:17.545+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T184115, end_date=20240307T184117
[2024-03-07T18:41:17.582+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T18:41:17.599+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
